on:
  issues:
    types: [opened]
  push:
    branches:
      - abdimoha-explore

jobs:
  new_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r src/tools/requirements.txt
          sudo apt-get update -y
          sudo apt-get install -y xpdf w3m
      - name: Update Repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./src/tools/update-repo.sh
          ./src/tools/update-repo.sh
      - name: Push changes to the repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git status
          git add README.md ATT\&CK.md
          git commit -m "Updated ${TODAYSDATE}"
          git push
          
