name: Issue Triggered Workflow

on:
  issues:
    types: [opened, edited]

jobs:
  new_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install -r src/tools/requirements.txt
          sudo apt-get update -y
          sudo apt-get install -y xpdf w3m
      - name: Update Repo
        run: |
          chmod +x ./src/tools/update-repo.sh
          ./src/tools/update-repo.sh
      - name: Push changes to the repo
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git status
          git add README.md ATT\&CK.md
          git diff-index --quiet HEAD || git commit -m "Updated on $(date -u)"
          git push
          
