on:
  issues:
    types: [opened]

jobs:
  new_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync Issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./src/tools/sync-issues.sh
          ./src/tools/sync-issues.sh
