on:
  issues:
    types: [opened]
  push:
    branches:
      - abdimoha-explore

jobs:
  new_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync Issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./src/tools/sync-issues.sh
          ./src/tools/sync-issues.sh
      # - name: Generate README.md.py
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     python3 src/tools/generate-README.md.py
      - name: Generate ATTACK.md.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 src/tools/generate-ATTACK.md.py
      - name: Retrieve Articles
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./src/tools/retrieve-articles.sh
          ./src/tools/retrieve-articles.sh
      - name: Lint Intel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./src/tools/intel-lint.sh
          ./src/tools/intel-lint.sh
      - name: Analyze articles
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          perl src/tools/analyse-articles.pl
      
          
