name: Process Issues
on:
  push:
    branches:
      - gpayne-workflow-testing
  schedule:
    - cron: '0 0 * * *' # Runs daily

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up cache for GH CLI
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/gh
          key: ${{ runner.os }}-gh-cli

      - name: Install GH CLI
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

      - name: Authenticate GH CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth login --with-token <<< "${GITHUB_TOKEN}"

  sync-issues:
    runs-on: ubuntu-20.04
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Restore GH CLI cache
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/gh
          key: ${{ runner.os }}-gh-cli
  
      - name: Install GH CLI
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh
  
      - name: Authenticate GH CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth login --with-token <<< "${GITHUB_TOKEN}"
  
      - name: Run sync-issues.sh
        run: ./src/tools/sync-issues.sh --date-filter
          
  generate-docs:
    runs-on: ubuntu-20.04
    needs: sync-issues
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Restore GH CLI cache
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/gh
          key: ${{ runner.os }}-gh-cli
  
      - name: Install Python Dependencies
        run: pip install pyattck
  
      - name: Generate README
        run: python3 src/tools/generate-README.md.py
  
      - name: Generate ATTACK
        run: python3 src/tools/generate-ATTACK.md.py
        

  manage-articles:
    runs-on: ubuntu-20.04
    needs: generate-docs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Restore GH CLI cache
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/gh
          key: ${{ runner.os }}-gh-cli

      - name: Retrieve articles
        run: ./src/tools/retrieve-articles.sh

      - name: Analyse articles
        run: perl src/tools/analyse-articles.pl

      - name: Lint articles
        run: ./src/tools/intel-lint.sh

  manage-binaries:
    runs-on: ubuntu-20.04
    needs: manage-articles
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Restore GH CLI cache
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/gh
          key: ${{ runner.os }}-gh-cli

      - name: Unpack binaries
        run: ./src/tools/unpack-binaries.sh

      - name: Scan binaries
        run: ./src/tools/scan-binaries.sh

      - name: Triage binaries
        run: ./src/tools/triage-binary.sh

      - name: Lint binaries
        run: ./src/tools/binary-lint.sh
