name: Process Issues
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs daily

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up cache for GH CLI
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/gh
          key: ${{ runner.os }}-gh-cli

      - name: Install GH CLI
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Authenticate GH CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth login --with-token <<< "${GITHUB_TOKEN}"

  sync-issues:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Restore GH CLI cache
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/gh
          key: ${{ runner.os }}-gh-cli

      - name: Authenticate GH CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth login --with-token <<< "${GITHUB_TOKEN}"

      - name: Run sync-issues.sh
        run: ./src/tools/sync-issues.sh --date-filter

  generate-docs:
    runs-on: ubuntu-latest
    needs: sync-issues
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Restore GH CLI cache
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/gh
          key: ${{ runner.os }}-gh-cli

      - name: Generate README
        run: python3 src/tools/generate-README.md.py

      - name: Generate ATT&CK
        run: python3 src/tools/generate-ATT&CK.md.py

  manage-articles:
    runs-on: ubuntu-latest
    needs: generate-docs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Restore GH CLI cache
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/gh
          key: ${{ runner.os }}-gh-cli

      - name: Retrieve articles
        run: ./src/tools/retrieve-articles.sh

      - name: Analyse articles
        run: perl src/tools/analyse-articles.pl

      - name: Lint articles
        run: ./src/tools/intel-lint.sh

      - name: Check duplicate articles
        run: ./src/tools/check-duplicate-articles.sh

  manage-binaries:
    runs-on: ubuntu-latest
    needs: manage-articles
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Restore GH CLI cache
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/gh
          key: ${{ runner.os }}-gh-cli

      - name: Unpack binaries
        run: ./src/tools/unpack-binaries.sh

      - name: Scan binaries
        run: ./src/tools/scan-binaries.sh

      - name: Triage binaries
        run: ./src/tools/triage-binary.sh

      - name: Lint binaries
        run: ./src/tools/binary-lint.sh
